package model;

public enum Enums {
    PROGRAM_STOPPED,
    ПРОГРАММА_ОСТАНОВЛЕНА,
    PROGRAM_SUCCESSFULLY_LAUNCHED,
    ПРОГРАММА_УСПЕШНО_ЗАПУЩЕНА,
    WRONG_DATE_FORMAT,
    НЕВЕРНЫЙ_ФОРМАТ_ДАТЫ,
    WRONG_DATE_FORMAT_IN_THE_HISTORY_FILE,
    НЕВЕРНЫЙ_ФОРМАТ_ДАТЫ_В_ФАЙЛЕ_ИСТОРИИ,
    FILE_READING_ERROR,
    ОШИБКА_В_ЧТЕНИИ_ФАЙЛА,
    FILE_WRITE_ERROR,
    ОШИБКА_В_ЗАПИСИ_ФАЙЛА,
    SETTINGS_FILE_READING_ERROR,
    ОШИБКА_В_ЧТЕНИИ_ФАЙЛА_НСТРОЕК,
    SETTINGS_FILE_WRITE_ERROR,
    ОШИБКА_В_ЗАПИСИ_ФАЙЛА_НСТРОЕК,
    SETTINGS_WONT_OVERWRITE_AFTER_THE_CHANGE_COMMAND,
    НАСТРОЙКИ_НЕ_ПЕРЕЗАПИСАЛИСЬ_ПОСЛЕ_КОМАНДЫ_ИЗМЕНЕНИЯ,
    FILE_SETTINGS_NOT_DETECTED_STANDARD_SETTINGS_INCLUDED,
    НАСТРОЕК_В_ФАЙЛЕ_НЕ_ОБНАРУЖЕНО_ВКЛЮЧЕНЫ_СТАНДАРТНЫЕ_НАСТРОЙКИ,
    FILE_HISTORY_NOT_DETECTED,
    ИСТОРИИ_В_ФАЙЛЕ_НЕ_ОБНАРУЖЕНО,
    HISTORY_FILE_READING_ERROR,
    ОШИБКА_В_ЧТЕНИИ_ФАЙЛА_ИСТОРИИ,
    SETTINGS_SUCCESSFULLY_READ,
    END,
    levels;
}
