package model;

public enum Outs {
    PROGRAM_STOPPED,
    ПРОГРАММА_ОСТАНОВЛЕНА,
    PROGRAM_SUCCESSFULLY_LAUNCHED,
    ПРОГРАММА_УСПЕШНО_ЗАПУЩЕНА,
    WRONG_DATE_FORMAT,
    НЕВЕРНЫЙ_ФОРМАТ_ДАТЫ,
    WRONG_DATE_FORMAT_IN_THE_HISTORY_FILE,
    НЕВЕРНЫЙ_ФОРМАТ_ДАТЫ_В_ФАЙЛЕ_ИСТОРИИ,
    FILE_READING_ERROR,
    ОШИБКА_В_ЧТЕНИИ_ФАЙЛА,
    FILE_WRITE_ERROR,
    ОШИБКА_В_ЗАПИСИ_ФАЙЛА,
    SETTINGS_FILE_READING_ERROR,
    ОШИБКА_В_ЧТЕНИИ_ФАЙЛА_НСТРОЕК,
    SETTINGS_FILE_WRITE_ERROR,
    ОШИБКА_В_ЗАПИСИ_ФАЙЛА_НСТРОЕК,
    SETTINGS_WONT_OVERWRITE_AFTER_THE_CHANGE_COMMAND,
    НАСТРОЙКИ_НЕ_ПЕРЕЗАПИСАЛИСЬ_ПОСЛЕ_КОМАНДЫ_ИЗМЕНЕНИЯ,
    FILE_SETTINGS_NOT_DETECTED_STANDARD_SETTINGS_INCLUDED,
    НАСТРОЕК_В_ФАЙЛЕ_НЕ_ОБНАРУЖЕНО_ВКЛЮЧЕНЫ_СТАНДАРТНЫЕ_НАСТРОЙКИ,
    FILE_HISTORY_NOT_DETECTED,
    ИСТОРИИ_В_ФАЙЛЕ_НЕ_ОБНАРУЖЕНО,
    HISTORY_FILE_READING_ERROR,
    ОШИБКА_В_ЧТЕНИИ_ФАЙЛА_ИСТОРИИ,
    SAVED_PATTERNS_FILE_WRITE_ERROR,
    ОШИБКА_В_ЗАПИСИ_ФАЙЛА_СОХРАНЕННЫХ_ПАТТЕРНОВ,
    SETTINGS_SUCCESSFULLY_READ,
    НАСТРОЙКИ_УСПЕШНО_СЧИТАНЫ,
    NO_PATTERN_TO_SAVE,
    НЕТ_ПАТТЕРНА_ДЛЯ_СОХРАНЕНИЯ,
    PATTERN_SUCCESSFULLY_SAVED,
    ПАТТЕРН_УСПЕШНО_СОХРАНЕН,
    NO_MATCHES_FOUND,
    СОВПАДЕНИЙ_НЕ_НАЙДЕНО,
    MATCHES_FOUND,
    НАЙДЕНО_СОВПАДЕНИЙ,
    CONVERTING_HISTORY,
    КОНВЕРТИРУЮ_ИСТОРИЮ,
    SORTING_HISTORY,
    СОРТИРУЮ_ИСТОРИЮ,
    REMOVING_EXTRA_FROM_HISTORY,
    УДАЛЯЮ_ЛИШНЕЕ_ИЗ_ИСТОРИЮ,

    SAVED_HISTORY_FILE_WRITE_ERROR,
    NO_HISTORY_TO_SAVE,
    HISTORY_SUCCESSFULLY_SAVED,

    REMOVED_LIKE_STORY_ITEMS,
    УДАЛЕНО_ОДИНАКОВЫХ_ЭЛЕМЕНТОВ_ИСТОРИИ
    ;
}
